services:
  nginxproxymanager:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginxproxymanager
    restart: unless-stopped
    ports:
      - "80:80"   
      - "443:443"  
      - "81:81"  
    volumes:
      - yourdiskpath/docker-data/nginxproxymanager/data:/data
      - yourdiskpath/docker-data/nginxproxymanager/letsencrypt:/etc/letsencrypt
    networks:
      - mybridge-net

networks:
  mybridge-net:
    external: true
